plugins {
    id 'base'
    id 'idea'
}

group = 'ru.nursafin'
version = '1.0-SNAPSHOT'

ext {
    lombokVersion = '1.18.44'
    junitVersion = '5.10.0'
    mockitoVersion = '5.23.0'
    jakartaPersistenceVersion = '3.2.0'
    hibernateVersion = '6.4.4.Final'
    postgresqlVersion = '42.7.7'
    slf4jVersion = '2.0.13'

}

subprojects {
    apply plugin: 'java-library'

    group = rootProject.group
    version = rootProject.version

    repositories {
        mavenCentral()
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(23)
        }
    }

    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    test {
        useJUnitPlatform()
        testLogging {
            events 'passed', 'skipped', 'failed'
        }
    }
}
