dependencies {
    api "jakarta.persistence:jakarta.persistence-api:${rootProject.ext.jakartaPersistenceVersion}"

    compileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    annotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"

    testCompileOnly "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
    testAnnotationProcessor "org.projectlombok:lombok:${rootProject.ext.lombokVersion}"
}