server:
  port: 8081

spring:
  application:
    name: rates-service
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: guest
    password: guest

app:
  rates:
    publish-interval-ms: 10000