dependencies {
    api project(':BankingSystemDomain')

    implementation "jakarta.persistence:jakarta.persistence-api:${rootProject.ext.jakartaPersistenceVersion}"

    testImplementation platform("org.junit:junit-bom:${rootProject.ext.junitVersion}")
    testImplementation "org.junit.jupiter:junit-jupiter"
    testRuntimeOnly "org.junit.platform:junit-platform-launcher"

    testImplementation "org.mockito:mockito-core:${rootProject.ext.mockitoVersion}"
    testImplementation "org.mockito:mockito-junit-jupiter:${rootProject.ext.mockitoVersion}"
}